definitions:
  rkgin.APIsResponse:
    properties:
      method:
        type: string
      name:
        type: string
      path:
        type: string
      port:
        type: integer
      sw_url:
        type: string
    type: object
  rkgin.ConfigResponse:
    properties:
      viper:
        type: string
    type: object
  rkgin.GCResponse:
    properties:
      mem_stat_after_gc:
        $ref: '#/definitions/rkinfo.MemStats'
      mem_stat_before_gc:
        $ref: '#/definitions/rkinfo.MemStats'
    type: object
  rkgin.HealthyResponse:
    properties:
      healthy:
        type: boolean
    type: object
  rkgin.SysResponse:
    properties:
      cpu_usage_percentage:
        type: number
      mem_usage_mb:
        type: integer
      mem_usage_percentage:
        type: number
      sys_up_time:
        type: string
    type: object
  rkinfo.BasicInfo:
    properties:
      application_name:
        type: string
      az:
        type: string
      domain:
        type: string
      gid:
        type: string
      realm:
        type: string
      region:
        type: string
      start_time:
        type: string
      uid:
        type: string
      up_time_sec:
        type: integer
      up_time_str:
        type: string
      username:
        type: string
    type: object
  rkinfo.MemStats:
    properties:
      force_gc_count:
        type: integer
      gc_count_total:
        type: integer
      last_gc_timestamp:
        type: string
      mem_alloc_byte:
        type: integer
      mem_usage_percentage:
        type: number
      sys_alloc_byte:
        type: integer
    type: object
  rkmetrics.ReqMetricsRK:
    properties:
      count:
        type: integer
      elapsed_nano_p50:
        type: number
      elapsed_nano_p90:
        type: number
      elapsed_nano_p99:
        type: number
      elapsed_nano_p999:
        type: number
      path:
        type: string
      res_code:
        items:
          $ref: '#/definitions/rkmetrics.ResCodeRK'
        type: array
    type: object
  rkmetrics.ResCodeRK:
    properties:
      count:
        type: integer
      res_code:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a common service with rk-gin.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: RK Swagger Example
  version: "1.0"
paths:
  /v1/rk/apis:
    get:
      operationId: "5"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/rkgin.APIsResponse'
            type: array
      summary: List APIs
  /v1/rk/config:
    get:
      operationId: "4"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkgin.ConfigResponse'
      summary: List Configs
  /v1/rk/gc:
    get:
      operationId: "2"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkgin.GCResponse'
      summary: Trigger GC
  /v1/rk/healthy:
    get:
      operationId: "1"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkgin.HealthyResponse'
      summary: Check healthy status
  /v1/rk/info:
    get:
      operationId: "3"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkinfo.BasicInfo'
      summary: Service Info
  /v1/rk/req:
    get:
      operationId: "7"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkmetrics.ReqMetricsRK'
      summary: Request Stat
  /v1/rk/sys:
    get:
      operationId: "6"
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rkgin.SysResponse'
      summary: System Stat
  /v1/rk/tv:
    get:
      operationId: "8"
      produces:
      - text/html
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: HTML page
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
